/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MovementsRouteImport } from './routes/movements'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipmentRoutersRouteImport } from './routes/equipment/routers'
import { Route as EquipmentPrintersRouteImport } from './routes/equipment/printers'
import { Route as EquipmentNotebooksRouteImport } from './routes/equipment/notebooks'
import { Route as EquipmentMonitorsRouteImport } from './routes/equipment/monitors'
import { Route as EquipmentCamerasRouteImport } from './routes/equipment/cameras'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsRoute = MovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoutersRoute = EquipmentRoutersRouteImport.update({
  id: '/equipment/routers',
  path: '/equipment/routers',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentPrintersRoute = EquipmentPrintersRouteImport.update({
  id: '/equipment/printers',
  path: '/equipment/printers',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentNotebooksRoute = EquipmentNotebooksRouteImport.update({
  id: '/equipment/notebooks',
  path: '/equipment/notebooks',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentMonitorsRoute = EquipmentMonitorsRouteImport.update({
  id: '/equipment/monitors',
  path: '/equipment/monitors',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentCamerasRoute = EquipmentCamerasRouteImport.update({
  id: '/equipment/cameras',
  path: '/equipment/cameras',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/movements': typeof MovementsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/equipment/cameras': typeof EquipmentCamerasRoute
  '/equipment/monitors': typeof EquipmentMonitorsRoute
  '/equipment/notebooks': typeof EquipmentNotebooksRoute
  '/equipment/printers': typeof EquipmentPrintersRoute
  '/equipment/routers': typeof EquipmentRoutersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/movements': typeof MovementsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/equipment/cameras': typeof EquipmentCamerasRoute
  '/equipment/monitors': typeof EquipmentMonitorsRoute
  '/equipment/notebooks': typeof EquipmentNotebooksRoute
  '/equipment/printers': typeof EquipmentPrintersRoute
  '/equipment/routers': typeof EquipmentRoutersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/movements': typeof MovementsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/equipment/cameras': typeof EquipmentCamerasRoute
  '/equipment/monitors': typeof EquipmentMonitorsRoute
  '/equipment/notebooks': typeof EquipmentNotebooksRoute
  '/equipment/printers': typeof EquipmentPrintersRoute
  '/equipment/routers': typeof EquipmentRoutersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/employees'
    | '/forgot-password'
    | '/login'
    | '/movements'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/equipment/cameras'
    | '/equipment/monitors'
    | '/equipment/notebooks'
    | '/equipment/printers'
    | '/equipment/routers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/employees'
    | '/forgot-password'
    | '/login'
    | '/movements'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/equipment/cameras'
    | '/equipment/monitors'
    | '/equipment/notebooks'
    | '/equipment/printers'
    | '/equipment/routers'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/employees'
    | '/forgot-password'
    | '/login'
    | '/movements'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/equipment/cameras'
    | '/equipment/monitors'
    | '/equipment/notebooks'
    | '/equipment/printers'
    | '/equipment/routers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EmployeesRoute: typeof EmployeesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MovementsRoute: typeof MovementsRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  EquipmentCamerasRoute: typeof EquipmentCamerasRoute
  EquipmentMonitorsRoute: typeof EquipmentMonitorsRoute
  EquipmentNotebooksRoute: typeof EquipmentNotebooksRoute
  EquipmentPrintersRoute: typeof EquipmentPrintersRoute
  EquipmentRoutersRoute: typeof EquipmentRoutersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements': {
      id: '/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof MovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/routers': {
      id: '/equipment/routers'
      path: '/equipment/routers'
      fullPath: '/equipment/routers'
      preLoaderRoute: typeof EquipmentRoutersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/printers': {
      id: '/equipment/printers'
      path: '/equipment/printers'
      fullPath: '/equipment/printers'
      preLoaderRoute: typeof EquipmentPrintersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/notebooks': {
      id: '/equipment/notebooks'
      path: '/equipment/notebooks'
      fullPath: '/equipment/notebooks'
      preLoaderRoute: typeof EquipmentNotebooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/monitors': {
      id: '/equipment/monitors'
      path: '/equipment/monitors'
      fullPath: '/equipment/monitors'
      preLoaderRoute: typeof EquipmentMonitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/cameras': {
      id: '/equipment/cameras'
      path: '/equipment/cameras'
      fullPath: '/equipment/cameras'
      preLoaderRoute: typeof EquipmentCamerasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EmployeesRoute: EmployeesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MovementsRoute: MovementsRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  EquipmentCamerasRoute: EquipmentCamerasRoute,
  EquipmentMonitorsRoute: EquipmentMonitorsRoute,
  EquipmentNotebooksRoute: EquipmentNotebooksRoute,
  EquipmentPrintersRoute: EquipmentPrintersRoute,
  EquipmentRoutersRoute: EquipmentRoutersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
